# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class BatchGetErrorFilesResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            errorFileUrl = schemas.StrSchema
            errorDetailsFileUrl = schemas.StrSchema
            __annotations__ = {
                "errorFileUrl": errorFileUrl,
                "errorDetailsFileUrl": errorDetailsFileUrl,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errorFileUrl"]) -> MetaOapg.properties.errorFileUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errorDetailsFileUrl"]) -> MetaOapg.properties.errorDetailsFileUrl: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["errorFileUrl", "errorDetailsFileUrl", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errorFileUrl"]) -> typing.Union[MetaOapg.properties.errorFileUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errorDetailsFileUrl"]) -> typing.Union[MetaOapg.properties.errorDetailsFileUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["errorFileUrl", "errorDetailsFileUrl", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        errorFileUrl: typing.Union[MetaOapg.properties.errorFileUrl, str, schemas.Unset] = schemas.unset,
        errorDetailsFileUrl: typing.Union[MetaOapg.properties.errorDetailsFileUrl, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BatchGetErrorFilesResponse':
        return super().__new__(
            cls,
            *args,
            errorFileUrl=errorFileUrl,
            errorDetailsFileUrl=errorDetailsFileUrl,
            _configuration=_configuration,
            **kwargs,
        )
