# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class MerchantTransactionIdStatusResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The response for the status request using merchantTransactionId as the query field.
    """


    class MetaOapg:
        required = {
            "result",
            "payments",
            "timestamp",
        }
        
        class properties:
        
            @staticmethod
            def result() -> typing.Type['Result']:
                return Result
            timestamp = schemas.DateTimeSchema
        
            @staticmethod
            def payments() -> typing.Type['MerchantTransactionIdStatusResponsePayments']:
                return MerchantTransactionIdStatusResponsePayments
            __annotations__ = {
                "result": result,
                "timestamp": timestamp,
                "payments": payments,
            }
    
    result: 'Result'
    payments: 'MerchantTransactionIdStatusResponsePayments'
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payments"]) -> 'MerchantTransactionIdStatusResponsePayments': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["result", "timestamp", "payments", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payments"]) -> 'MerchantTransactionIdStatusResponsePayments': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["result", "timestamp", "payments", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        result: 'Result',
        payments: 'MerchantTransactionIdStatusResponsePayments',
        timestamp: typing.Union[MetaOapg.properties.timestamp, str, datetime, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MerchantTransactionIdStatusResponse':
        return super().__new__(
            cls,
            *args,
            result=result,
            payments=payments,
            timestamp=timestamp,
            _configuration=_configuration,
            **kwargs,
        )

from peach_payments_python_sdk.model.merchant_transaction_id_status_response_payments import MerchantTransactionIdStatusResponsePayments
from peach_payments_python_sdk.model.result import Result
