# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class MerchantWebhookDataPayloadMerchant(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Merchant object with data relevant to an EFTsecure transaction.
    """


    class MetaOapg:
        
        class properties:
            apiUsername = schemas.StrSchema
            eftId = schemas.StrSchema
            __annotations__ = {
                "apiUsername": apiUsername,
                "eftId": eftId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apiUsername"]) -> MetaOapg.properties.apiUsername: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["eftId"]) -> MetaOapg.properties.eftId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["apiUsername", "eftId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apiUsername"]) -> typing.Union[MetaOapg.properties.apiUsername, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["eftId"]) -> typing.Union[MetaOapg.properties.eftId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["apiUsername", "eftId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        apiUsername: typing.Union[MetaOapg.properties.apiUsername, str, schemas.Unset] = schemas.unset,
        eftId: typing.Union[MetaOapg.properties.eftId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MerchantWebhookDataPayloadMerchant':
        return super().__new__(
            cls,
            *args,
            apiUsername=apiUsername,
            eftId=eftId,
            _configuration=_configuration,
            **kwargs,
        )
