# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class PaymentBrand(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The payment brand specifies the method of payment for the request.
    """
    
    @schemas.classproperty
    def EFTSECURE(cls):
        return cls("EFTSECURE")
    
    @schemas.classproperty
    def PAYFLEX(cls):
        return cls("PAYFLEX")
    
    @schemas.classproperty
    def ZEROPAY(cls):
        return cls("ZEROPAY")
    
    @schemas.classproperty
    def FINCHOICEPAY(cls):
        return cls("FINCHOICEPAY")
    
    @schemas.classproperty
    def _1FORYOU(cls):
        return cls("1FORYOU")
    
    @schemas.classproperty
    def MASTERPASS(cls):
        return cls("MASTERPASS")
    
    @schemas.classproperty
    def MPESA(cls):
        return cls("MPESA")
    
    @schemas.classproperty
    def BLINKBYEMTEL(cls):
        return cls("BLINKBYEMTEL")
    
    @schemas.classproperty
    def MOBICRED(cls):
        return cls("MOBICRED")
    
    @schemas.classproperty
    def CAPITECPAY(cls):
        return cls("CAPITECPAY")
    
    @schemas.classproperty
    def NEDBANKDIRECTEFT(cls):
        return cls("NEDBANKDIRECTEFT")
    
    @schemas.classproperty
    def MCBJUICE(cls):
        return cls("MCBJUICE")
