# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class PaymentResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "result",
            "amount",
            "paymentBrand",
            "currency",
            "customParameters",
            "id",
            "paymentType",
            "timestamp",
        }
        
        class properties:
        
            @staticmethod
            def amount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def currency() -> typing.Type['Currency']:
                return Currency
        
            @staticmethod
            def paymentBrand() -> typing.Type['PaymentBrand']:
                return PaymentBrand
        
            @staticmethod
            def paymentType() -> typing.Type['PaymentType']:
                return PaymentType
        
            @staticmethod
            def result() -> typing.Type['Result']:
                return Result
            customParameters = schemas.DictSchema
            timestamp = schemas.DateTimeSchema
        
            @staticmethod
            def id() -> typing.Type['UniqueId']:
                return UniqueId
        
            @staticmethod
            def resultDetails() -> typing.Type['ResultDetails']:
                return ResultDetails
        
            @staticmethod
            def redirect() -> typing.Type['Redirect']:
                return Redirect
        
            @staticmethod
            def connectorTxID1() -> typing.Type['ConnectorTxID1']:
                return ConnectorTxID1
        
            @staticmethod
            def connectorTxID2() -> typing.Type['ConnectorTxID2']:
                return ConnectorTxID2
        
            @staticmethod
            def merchantTransactionId() -> typing.Type['MerchantTransactionId']:
                return MerchantTransactionId
        
            @staticmethod
            def merchantInvoiceId() -> typing.Type['MerchantInvoiceId']:
                return MerchantInvoiceId
            shopperResultUrl = schemas.StrSchema
        
            @staticmethod
            def virtualAccount() -> typing.Type['VirtualAccount']:
                return VirtualAccount
            transactionExpiryTimestamp = schemas.DateTimeSchema
            __annotations__ = {
                "amount": amount,
                "currency": currency,
                "paymentBrand": paymentBrand,
                "paymentType": paymentType,
                "result": result,
                "customParameters": customParameters,
                "timestamp": timestamp,
                "id": id,
                "resultDetails": resultDetails,
                "redirect": redirect,
                "connectorTxID1": connectorTxID1,
                "connectorTxID2": connectorTxID2,
                "merchantTransactionId": merchantTransactionId,
                "merchantInvoiceId": merchantInvoiceId,
                "shopperResultUrl": shopperResultUrl,
                "virtualAccount": virtualAccount,
                "transactionExpiryTimestamp": transactionExpiryTimestamp,
            }
    
    result: 'Result'
    amount: 'Amount'
    paymentBrand: 'PaymentBrand'
    currency: 'Currency'
    customParameters: MetaOapg.properties.customParameters
    id: 'UniqueId'
    paymentType: 'PaymentType'
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentBrand"]) -> 'PaymentBrand': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentType"]) -> 'PaymentType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customParameters"]) -> MetaOapg.properties.customParameters: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> 'UniqueId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resultDetails"]) -> 'ResultDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redirect"]) -> 'Redirect': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectorTxID1"]) -> 'ConnectorTxID1': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectorTxID2"]) -> 'ConnectorTxID2': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantTransactionId"]) -> 'MerchantTransactionId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> 'MerchantInvoiceId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shopperResultUrl"]) -> MetaOapg.properties.shopperResultUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["virtualAccount"]) -> 'VirtualAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactionExpiryTimestamp"]) -> MetaOapg.properties.transactionExpiryTimestamp: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "currency", "paymentBrand", "paymentType", "result", "customParameters", "timestamp", "id", "resultDetails", "redirect", "connectorTxID1", "connectorTxID2", "merchantTransactionId", "merchantInvoiceId", "shopperResultUrl", "virtualAccount", "transactionExpiryTimestamp", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentBrand"]) -> 'PaymentBrand': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentType"]) -> 'PaymentType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customParameters"]) -> MetaOapg.properties.customParameters: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> 'UniqueId': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resultDetails"]) -> typing.Union['ResultDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redirect"]) -> typing.Union['Redirect', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectorTxID1"]) -> typing.Union['ConnectorTxID1', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectorTxID2"]) -> typing.Union['ConnectorTxID2', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantTransactionId"]) -> typing.Union['MerchantTransactionId', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> typing.Union['MerchantInvoiceId', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shopperResultUrl"]) -> typing.Union[MetaOapg.properties.shopperResultUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["virtualAccount"]) -> typing.Union['VirtualAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactionExpiryTimestamp"]) -> typing.Union[MetaOapg.properties.transactionExpiryTimestamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "currency", "paymentBrand", "paymentType", "result", "customParameters", "timestamp", "id", "resultDetails", "redirect", "connectorTxID1", "connectorTxID2", "merchantTransactionId", "merchantInvoiceId", "shopperResultUrl", "virtualAccount", "transactionExpiryTimestamp", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        result: 'Result',
        amount: 'Amount',
        paymentBrand: 'PaymentBrand',
        currency: 'Currency',
        customParameters: typing.Union[MetaOapg.properties.customParameters, dict, frozendict.frozendict, ],
        id: 'UniqueId',
        paymentType: 'PaymentType',
        timestamp: typing.Union[MetaOapg.properties.timestamp, str, datetime, ],
        resultDetails: typing.Union['ResultDetails', schemas.Unset] = schemas.unset,
        redirect: typing.Union['Redirect', schemas.Unset] = schemas.unset,
        connectorTxID1: typing.Union['ConnectorTxID1', schemas.Unset] = schemas.unset,
        connectorTxID2: typing.Union['ConnectorTxID2', schemas.Unset] = schemas.unset,
        merchantTransactionId: typing.Union['MerchantTransactionId', schemas.Unset] = schemas.unset,
        merchantInvoiceId: typing.Union['MerchantInvoiceId', schemas.Unset] = schemas.unset,
        shopperResultUrl: typing.Union[MetaOapg.properties.shopperResultUrl, str, schemas.Unset] = schemas.unset,
        virtualAccount: typing.Union['VirtualAccount', schemas.Unset] = schemas.unset,
        transactionExpiryTimestamp: typing.Union[MetaOapg.properties.transactionExpiryTimestamp, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentResponse':
        return super().__new__(
            cls,
            *args,
            result=result,
            amount=amount,
            paymentBrand=paymentBrand,
            currency=currency,
            customParameters=customParameters,
            id=id,
            paymentType=paymentType,
            timestamp=timestamp,
            resultDetails=resultDetails,
            redirect=redirect,
            connectorTxID1=connectorTxID1,
            connectorTxID2=connectorTxID2,
            merchantTransactionId=merchantTransactionId,
            merchantInvoiceId=merchantInvoiceId,
            shopperResultUrl=shopperResultUrl,
            virtualAccount=virtualAccount,
            transactionExpiryTimestamp=transactionExpiryTimestamp,
            _configuration=_configuration,
            **kwargs,
        )

from peach_payments_python_sdk.model.amount import Amount
from peach_payments_python_sdk.model.connector_tx_id1 import ConnectorTxID1
from peach_payments_python_sdk.model.connector_tx_id2 import ConnectorTxID2
from peach_payments_python_sdk.model.currency import Currency
from peach_payments_python_sdk.model.merchant_invoice_id import MerchantInvoiceId
from peach_payments_python_sdk.model.merchant_transaction_id import MerchantTransactionId
from peach_payments_python_sdk.model.payment_brand import PaymentBrand
from peach_payments_python_sdk.model.payment_type import PaymentType
from peach_payments_python_sdk.model.redirect import Redirect
from peach_payments_python_sdk.model.result import Result
from peach_payments_python_sdk.model.result_details import ResultDetails
from peach_payments_python_sdk.model.unique_id import UniqueId
from peach_payments_python_sdk.model.virtual_account import VirtualAccount
