# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class QueryStatusResponsePayment(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            linkId = schemas.StrSchema
            linkUrl = schemas.StrSchema
            amount = schemas.NumberSchema
            
            
            class status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "initiated": "INITIATED",
                        "processing": "PROCESSING",
                        "expired": "EXPIRED",
                        "cancelled": "CANCELLED",
                        "completed": "COMPLETED",
                    }
                
                @schemas.classproperty
                def INITIATED(cls):
                    return cls("initiated")
                
                @schemas.classproperty
                def PROCESSING(cls):
                    return cls("processing")
                
                @schemas.classproperty
                def EXPIRED(cls):
                    return cls("expired")
                
                @schemas.classproperty
                def CANCELLED(cls):
                    return cls("cancelled")
                
                @schemas.classproperty
                def COMPLETED(cls):
                    return cls("completed")
            
            
            class currency(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ZAR": "ZAR",
                        "KES": "KES",
                        "USD": "USD",
                    }
                
                @schemas.classproperty
                def ZAR(cls):
                    return cls("ZAR")
                
                @schemas.classproperty
                def KES(cls):
                    return cls("KES")
                
                @schemas.classproperty
                def USD(cls):
                    return cls("USD")
            merchantInvoiceId = schemas.StrSchema
            entityId = schemas.StrSchema
            
            
            class notes(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 140
            expiryTime = schemas.StrSchema
            batchId = schemas.StrSchema
            __annotations__ = {
                "linkId": linkId,
                "linkUrl": linkUrl,
                "amount": amount,
                "status": status,
                "currency": currency,
                "merchantInvoiceId": merchantInvoiceId,
                "entityId": entityId,
                "notes": notes,
                "expiryTime": expiryTime,
                "batchId": batchId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["linkId"]) -> MetaOapg.properties.linkId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["linkUrl"]) -> MetaOapg.properties.linkUrl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> MetaOapg.properties.merchantInvoiceId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["entityId"]) -> MetaOapg.properties.entityId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["notes"]) -> MetaOapg.properties.notes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiryTime"]) -> MetaOapg.properties.expiryTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["batchId"]) -> MetaOapg.properties.batchId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["linkId", "linkUrl", "amount", "status", "currency", "merchantInvoiceId", "entityId", "notes", "expiryTime", "batchId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["linkId"]) -> typing.Union[MetaOapg.properties.linkId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["linkUrl"]) -> typing.Union[MetaOapg.properties.linkUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> typing.Union[MetaOapg.properties.amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> typing.Union[MetaOapg.properties.currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> typing.Union[MetaOapg.properties.merchantInvoiceId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["entityId"]) -> typing.Union[MetaOapg.properties.entityId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["notes"]) -> typing.Union[MetaOapg.properties.notes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiryTime"]) -> typing.Union[MetaOapg.properties.expiryTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["batchId"]) -> typing.Union[MetaOapg.properties.batchId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["linkId", "linkUrl", "amount", "status", "currency", "merchantInvoiceId", "entityId", "notes", "expiryTime", "batchId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        linkId: typing.Union[MetaOapg.properties.linkId, str, schemas.Unset] = schemas.unset,
        linkUrl: typing.Union[MetaOapg.properties.linkUrl, str, schemas.Unset] = schemas.unset,
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        currency: typing.Union[MetaOapg.properties.currency, str, schemas.Unset] = schemas.unset,
        merchantInvoiceId: typing.Union[MetaOapg.properties.merchantInvoiceId, str, schemas.Unset] = schemas.unset,
        entityId: typing.Union[MetaOapg.properties.entityId, str, schemas.Unset] = schemas.unset,
        notes: typing.Union[MetaOapg.properties.notes, str, schemas.Unset] = schemas.unset,
        expiryTime: typing.Union[MetaOapg.properties.expiryTime, str, schemas.Unset] = schemas.unset,
        batchId: typing.Union[MetaOapg.properties.batchId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'QueryStatusResponsePayment':
        return super().__new__(
            cls,
            *args,
            linkId=linkId,
            linkUrl=linkUrl,
            amount=amount,
            status=status,
            currency=currency,
            merchantInvoiceId=merchantInvoiceId,
            entityId=entityId,
            notes=notes,
            expiryTime=expiryTime,
            batchId=batchId,
            _configuration=_configuration,
            **kwargs,
        )
