# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class StatusQueryPaymentStatusResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def payment() -> typing.Type['QueryStatusResponse']:
                return QueryStatusResponse
        
            @staticmethod
            def audit() -> typing.Type['StatusQueryPaymentStatusResponseAudit']:
                return StatusQueryPaymentStatusResponseAudit
            __annotations__ = {
                "payment": payment,
                "audit": audit,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payment"]) -> 'QueryStatusResponse': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audit"]) -> 'StatusQueryPaymentStatusResponseAudit': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["payment", "audit", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payment"]) -> typing.Union['QueryStatusResponse', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audit"]) -> typing.Union['StatusQueryPaymentStatusResponseAudit', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payment", "audit", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        payment: typing.Union['QueryStatusResponse', schemas.Unset] = schemas.unset,
        audit: typing.Union['StatusQueryPaymentStatusResponseAudit', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'StatusQueryPaymentStatusResponse':
        return super().__new__(
            cls,
            *args,
            payment=payment,
            audit=audit,
            _configuration=_configuration,
            **kwargs,
        )

from peach_payments_python_sdk.model.query_status_response import QueryStatusResponse
from peach_payments_python_sdk.model.status_query_payment_status_response_audit import StatusQueryPaymentStatusResponseAudit
