# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from peach_payments_python_sdk import schemas  # noqa: F401


class TransactionIdStatusResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The response for the status request using transactionId as the query field.
    """


    class MetaOapg:
        required = {
            "result",
            "amount",
            "paymentBrand",
            "merchantTransactionId",
            "currency",
            "customParameters",
            "id",
            "connectorTxID1",
            "paymentType",
            "timestamp",
        }
        
        class properties:
        
            @staticmethod
            def id() -> typing.Type['UniqueId']:
                return UniqueId
        
            @staticmethod
            def merchantTransactionId() -> typing.Type['MerchantTransactionId']:
                return MerchantTransactionId
        
            @staticmethod
            def amount() -> typing.Type['Amount']:
                return Amount
        
            @staticmethod
            def currency() -> typing.Type['Currency']:
                return Currency
        
            @staticmethod
            def paymentBrand() -> typing.Type['PaymentBrand']:
                return PaymentBrand
        
            @staticmethod
            def paymentType() -> typing.Type['PaymentType']:
                return PaymentType
        
            @staticmethod
            def result() -> typing.Type['Result']:
                return Result
        
            @staticmethod
            def connectorTxID1() -> typing.Type['ConnectorTxID1']:
                return ConnectorTxID1
            timestamp = schemas.DateTimeSchema
            customParameters = schemas.DictSchema
        
            @staticmethod
            def resultDetails() -> typing.Type['ResultDetails']:
                return ResultDetails
        
            @staticmethod
            def merchantInvoiceId() -> typing.Type['MerchantInvoiceId']:
                return MerchantInvoiceId
        
            @staticmethod
            def bank() -> typing.Type['Bank']:
                return Bank
        
            @staticmethod
            def card() -> typing.Type['ResponseCard']:
                return ResponseCard
        
            @staticmethod
            def recon() -> typing.Type['Recon']:
                return Recon
            __annotations__ = {
                "id": id,
                "merchantTransactionId": merchantTransactionId,
                "amount": amount,
                "currency": currency,
                "paymentBrand": paymentBrand,
                "paymentType": paymentType,
                "result": result,
                "connectorTxID1": connectorTxID1,
                "timestamp": timestamp,
                "customParameters": customParameters,
                "resultDetails": resultDetails,
                "merchantInvoiceId": merchantInvoiceId,
                "bank": bank,
                "card": card,
                "recon": recon,
            }
    
    result: 'Result'
    amount: 'Amount'
    paymentBrand: 'PaymentBrand'
    merchantTransactionId: 'MerchantTransactionId'
    currency: 'Currency'
    customParameters: MetaOapg.properties.customParameters
    id: 'UniqueId'
    connectorTxID1: 'ConnectorTxID1'
    paymentType: 'PaymentType'
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> 'UniqueId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantTransactionId"]) -> 'MerchantTransactionId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> 'Amount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentBrand"]) -> 'PaymentBrand': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paymentType"]) -> 'PaymentType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["connectorTxID1"]) -> 'ConnectorTxID1': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customParameters"]) -> MetaOapg.properties.customParameters: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resultDetails"]) -> 'ResultDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> 'MerchantInvoiceId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank"]) -> 'Bank': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["card"]) -> 'ResponseCard': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recon"]) -> 'Recon': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "merchantTransactionId", "amount", "currency", "paymentBrand", "paymentType", "result", "connectorTxID1", "timestamp", "customParameters", "resultDetails", "merchantInvoiceId", "bank", "card", "recon", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> 'UniqueId': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantTransactionId"]) -> 'MerchantTransactionId': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> 'Amount': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> 'Currency': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentBrand"]) -> 'PaymentBrand': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paymentType"]) -> 'PaymentType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["result"]) -> 'Result': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["connectorTxID1"]) -> 'ConnectorTxID1': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customParameters"]) -> MetaOapg.properties.customParameters: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resultDetails"]) -> typing.Union['ResultDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantInvoiceId"]) -> typing.Union['MerchantInvoiceId', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank"]) -> typing.Union['Bank', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["card"]) -> typing.Union['ResponseCard', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recon"]) -> typing.Union['Recon', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "merchantTransactionId", "amount", "currency", "paymentBrand", "paymentType", "result", "connectorTxID1", "timestamp", "customParameters", "resultDetails", "merchantInvoiceId", "bank", "card", "recon", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        result: 'Result',
        amount: 'Amount',
        paymentBrand: 'PaymentBrand',
        merchantTransactionId: 'MerchantTransactionId',
        currency: 'Currency',
        customParameters: typing.Union[MetaOapg.properties.customParameters, dict, frozendict.frozendict, ],
        id: 'UniqueId',
        connectorTxID1: 'ConnectorTxID1',
        paymentType: 'PaymentType',
        timestamp: typing.Union[MetaOapg.properties.timestamp, str, datetime, ],
        resultDetails: typing.Union['ResultDetails', schemas.Unset] = schemas.unset,
        merchantInvoiceId: typing.Union['MerchantInvoiceId', schemas.Unset] = schemas.unset,
        bank: typing.Union['Bank', schemas.Unset] = schemas.unset,
        card: typing.Union['ResponseCard', schemas.Unset] = schemas.unset,
        recon: typing.Union['Recon', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TransactionIdStatusResponse':
        return super().__new__(
            cls,
            *args,
            result=result,
            amount=amount,
            paymentBrand=paymentBrand,
            merchantTransactionId=merchantTransactionId,
            currency=currency,
            customParameters=customParameters,
            id=id,
            connectorTxID1=connectorTxID1,
            paymentType=paymentType,
            timestamp=timestamp,
            resultDetails=resultDetails,
            merchantInvoiceId=merchantInvoiceId,
            bank=bank,
            card=card,
            recon=recon,
            _configuration=_configuration,
            **kwargs,
        )

from peach_payments_python_sdk.model.amount import Amount
from peach_payments_python_sdk.model.bank import Bank
from peach_payments_python_sdk.model.connector_tx_id1 import ConnectorTxID1
from peach_payments_python_sdk.model.currency import Currency
from peach_payments_python_sdk.model.merchant_invoice_id import MerchantInvoiceId
from peach_payments_python_sdk.model.merchant_transaction_id import MerchantTransactionId
from peach_payments_python_sdk.model.payment_brand import PaymentBrand
from peach_payments_python_sdk.model.payment_type import PaymentType
from peach_payments_python_sdk.model.recon import Recon
from peach_payments_python_sdk.model.response_card import ResponseCard
from peach_payments_python_sdk.model.result import Result
from peach_payments_python_sdk.model.result_details import ResultDetails
from peach_payments_python_sdk.model.unique_id import UniqueId
