# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from peach_payments_python_sdk.paths.api_channels_entity_id_payments_batches.post import GenerateLinkRaw
from peach_payments_python_sdk.paths.api_channels_entity_id_payments_batches.get import GetBatchStatusesRaw
from peach_payments_python_sdk.paths.api_batches_batch_id_files.get import GetErrorFilesRaw
from peach_payments_python_sdk.paths.api_batches_batch_id.get import LinkStatusGetRaw


class BatchApiRaw(
    GenerateLinkRaw,
    GetBatchStatusesRaw,
    GetErrorFilesRaw,
    LinkStatusGetRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
