# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from peach_payments_python_sdk.paths.api_channels_entity_id_payments_batches.post import GenerateLink
from peach_payments_python_sdk.paths.api_channels_entity_id_payments_batches.get import GetBatchStatuses
from peach_payments_python_sdk.paths.api_batches_batch_id_files.get import GetErrorFiles
from peach_payments_python_sdk.paths.api_batches_batch_id.get import LinkStatusGet
from peach_payments_python_sdk.apis.tags.batch_api_raw import BatchApiRaw


class BatchApi(
    GenerateLink,
    GetBatchStatuses,
    GetErrorFiles,
    LinkStatusGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BatchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BatchApiRaw(api_client)
