# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from peach_payments_python_sdk.paths.v2_checkout.post import InitiateCheckoutInstance
from peach_payments_python_sdk.apis.tags.checkout_v2_generation_api_raw import CheckoutV2GenerationApiRaw


class CheckoutV2GenerationApi(
    InitiateCheckoutInstance,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CheckoutV2GenerationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CheckoutV2GenerationApiRaw(api_client)
