# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from peach_payments_python_sdk.paths.checkout.post import InitiatePayment
from peach_payments_python_sdk.paths.checkout_initiate.post import InitiateRedirectCheckout
from peach_payments_python_sdk.paths.checkout_validate.post import ValidateRequest
from peach_payments_python_sdk.apis.tags.checkout_generation_api_raw import CheckoutGenerationApiRaw


class CheckoutGenerationApi(
    InitiatePayment,
    InitiateRedirectCheckout,
    ValidateRequest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CheckoutGenerationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CheckoutGenerationApiRaw(api_client)
