# coding: utf-8

"""
    Payments API inbound

    The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

    The version of the OpenAPI document: 2.0.0
    Contact: support@peachpayments.com
    Created by: https://support.peachpayments.com/support/home
"""

from peach_payments_python_sdk.paths.payments.post import InitiateDebitTransactionRaw
from peach_payments_python_sdk.paths.payments_unique_id.get import QueryTransactionByIdRaw
from peach_payments_python_sdk.paths.payments_unique_id.post import RefundTransactionRaw
from peach_payments_python_sdk.paths.payments.get import StatusRaw


class PaymentsAPIInboundApiRaw(
    InitiateDebitTransactionRaw,
    QueryTransactionByIdRaw,
    RefundTransactionRaw,
    StatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
